-- Migration: 003_create_signals
-- Description: Create signals table for storing strategy signals
-- Created: 2025-11-14

-- Create signals table
CREATE TABLE IF NOT EXISTS signals (
    signal_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ts TIMESTAMPTZ NOT NULL,
    strategy_id VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('BUY', 'SELL', 'HOLD')),
    strength NUMERIC(3, 2) NOT NULL CHECK (strength >= 0 AND strength <= 1),
    target_price NUMERIC(20, 2),
    stop_loss NUMERIC(20, 2),
    take_profit NUMERIC(20, 2),
    reason TEXT NOT NULL,
    params_hash VARCHAR(64) NOT NULL,
    correlation_id UUID NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index on timestamp (most recent signals first)
CREATE INDEX IF NOT EXISTS idx_signals_ts ON signals(ts DESC);

-- Create composite index for symbol and timestamp
CREATE INDEX IF NOT EXISTS idx_signals_symbol_ts ON signals(symbol, ts DESC);

-- Create index on strategy_id
CREATE INDEX IF NOT EXISTS idx_signals_strategy_id ON signals(strategy_id);

-- Create index on direction
CREATE INDEX IF NOT EXISTS idx_signals_direction ON signals(direction);

-- Create index on correlation_id for tracing
CREATE INDEX IF NOT EXISTS idx_signals_correlation_id ON signals(correlation_id);

-- Create index on params_hash for tracking strategy versions
CREATE INDEX IF NOT EXISTS idx_signals_params_hash ON signals(params_hash);

-- Add comments
COMMENT ON TABLE signals IS 'Trading signals generated by strategies';
COMMENT ON COLUMN signals.strength IS 'Signal confidence level (0.0 to 1.0)';
COMMENT ON COLUMN signals.params_hash IS 'Hash of strategy parameters for version tracking';
COMMENT ON COLUMN signals.correlation_id IS 'Correlation ID for request tracing';
