/**
 * Strategy types for trading system
 */

import type { Symbol, Timestamp, Direction, CorrelationId } from './common';
import type { MarketData } from './market';

/**
 * Trading signal generated by a strategy
 */
export interface Signal {
  readonly signalId: string;
  readonly timestamp: Timestamp;
  readonly strategyId: string;
  readonly symbol: Symbol;
  readonly direction: Direction;
  readonly strength: number; // 0.0 to 1.0, confidence level
  readonly targetPrice?: number;
  readonly stopLoss?: number;
  readonly takeProfit?: number;
  readonly reason: string; // Human-readable explanation
  readonly paramsHash: string; // Hash of strategy parameters
  readonly correlationId: CorrelationId;
  readonly metadata?: Record<string, unknown>;
}

/**
 * Strategy parameters interface
 */
export interface StrategyParams {
  readonly [key: string]: string | number | boolean | undefined;
}

/**
 * Strategy interface that all trading strategies must implement
 */
export interface Strategy {
  /**
   * Unique strategy identifier
   */
  readonly strategyId: string;

  /**
   * Strategy name
   */
  readonly name: string;

  /**
   * Strategy description
   */
  readonly description: string;

  /**
   * Strategy parameters
   */
  readonly params: StrategyParams;

  /**
   * Analyze market data and generate trading signal
   */
  analyze(marketData: MarketData): Promise<Signal>;

  /**
   * Get hash of current parameters for version tracking
   */
  getParamsHash(): string;

  /**
   * Validate strategy parameters
   */
  validateParams(): boolean;
}

/**
 * Strategy performance metrics
 */
export interface StrategyPerformance {
  readonly strategyId: string;
  readonly startDate: Timestamp;
  readonly endDate: Timestamp;
  readonly totalSignals: number;
  readonly profitableSignals: number;
  readonly unprofitableSignals: number;
  readonly winRate: number;
  readonly averageReturn: number;
  readonly totalReturn: number;
  readonly maxDrawdown: number;
  readonly sharpeRatio: number;
  readonly calmarRatio: number;
}

/**
 * Backtest configuration
 */
export interface BacktestConfig {
  readonly strategyId: string;
  readonly symbols: readonly Symbol[];
  readonly startDate: string; // YYYY-MM-DD
  readonly endDate: string; // YYYY-MM-DD
  readonly initialCapital: number;
  readonly commission: number; // Per trade commission
  readonly slippage: number; // Expected slippage percentage
}

/**
 * Backtest result
 */
export interface BacktestResult {
  readonly config: BacktestConfig;
  readonly performance: StrategyPerformance;
  readonly trades: readonly BacktestTrade[];
  readonly equityCurve: readonly EquityPoint[];
  readonly statistics: BacktestStatistics;
}

/**
 * Backtest trade
 */
export interface BacktestTrade {
  readonly tradeId: string;
  readonly symbol: Symbol;
  readonly entryDate: Timestamp;
  readonly exitDate: Timestamp;
  readonly entryPrice: number;
  readonly exitPrice: number;
  readonly quantity: number;
  readonly pnl: number;
  readonly pnlPercentage: number;
  readonly commission: number;
  readonly signal: Signal;
}

/**
 * Equity curve point
 */
export interface EquityPoint {
  readonly timestamp: Timestamp;
  readonly equity: number;
  readonly cash: number;
  readonly positions: number;
}

/**
 * Backtest statistics
 */
export interface BacktestStatistics {
  readonly totalTrades: number;
  readonly winningTrades: number;
  readonly losingTrades: number;
  readonly winRate: number;
  readonly averageWin: number;
  readonly averageLoss: number;
  readonly largestWin: number;
  readonly largestLoss: number;
  readonly profitFactor: number;
  readonly maxDrawdown: number;
  readonly maxDrawdownDuration: number; // Days
  readonly sharpeRatio: number;
  readonly sortinoRatio: number;
  readonly calmarRatio: number;
  readonly avgTradeLength: number; // Days
  readonly expectancy: number; // Average trade PnL
}

/**
 * Strategy state for stateful strategies
 */
export interface StrategyState {
  readonly strategyId: string;
  readonly lastUpdate: Timestamp;
  readonly data: Record<string, unknown>;
}

/**
 * Technical indicator interface
 */
export interface Indicator {
  readonly name: string;
  calculate(data: readonly number[]): number | number[] | undefined;
}

/**
 * Moving average types
 */
export enum MovingAverageType {
  SIMPLE = 'SIMPLE', // SMA
  EXPONENTIAL = 'EXPONENTIAL', // EMA
  WEIGHTED = 'WEIGHTED', // WMA
}
